name: santali_calendar
description: A lunisolar calendar for Santali people based on astronomical calculations.

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

version: 1.0.4
license: MIT
repository: https://github.com/wesantal/santali-calendar-dart
homepage: https://calendar.wesantal.org
documentation: https://calendar.wesantal.org/docs

environment:
  sdk: ^3.13.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

topics:
  - santali
  - calendar
  - ol-chiki
  - date
  - indigenous-calendar
